/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package i.shatalov.teamproject.database;

import java.sql.*;

public class updateUser {
  //JDBC driver name and database URL
  static final String JDBC_DRIVER = "com.mysql.jdbc.Driver";
  static final String DB_URL = "jdbc:mysql://localhost:3306/robots";

  //Database credentials
  static final String USER = "root";
  static final String PASS = "Pai4Piqwerty";

  public void savePlayer(Player player) {
    Connection conn = null;
    Statement stmt;
    try {

      //Register JDBC driver
      Class.forName(JDBC_DRIVER);

      //Open a connection
      System.out.println("Connecting to a selected database...");
      conn = DriverManager.getConnection(DB_URL, USER, PASS);
      System.out.println("Connected database successfully.");

      //Checking is there already user with
      stmt = conn.createStatement();
      String sql = "SELECT LogName FROM users";
      ResultSet resultSet = stmt.executeQuery(sql);
      String ifCheck;
      while (resultSet.next()) {
        ifCheck = resultSet.getString("LogName");
        if (ifCheck == player.LogName) {
          System.out.println("Record with given id already exist");
          return;
        }
      }

      //Creating statement for DataBase tpo insert new record (new user)
      System.out.println("Inserting given records in the table...");
      stmt = conn.createStatement();
      sql = "INSERT INTO users " +
          "VALUES (\'" + player.LogName +
          "', \'" + player.Password + "', \'" + player.AccType + "' )";
      stmt.executeUpdate(sql);
      System.out.println("Records inserted.");
    } catch (Exception se) {
      //Handle errors for JDBC
      se.printStackTrace();
    }
    finally {
      //finally block used to close resources
      try {
        if (conn != null)
          conn.close();
      } catch (SQLException se) {
        se.printStackTrace();
      }//end finally try
    }//end try
    System.out.println("--END--");
  }

  public Player getPlayer(String name){
    Connection conn = null;
    Statement stmt;
    Player player = null;
    try {

      System.out.println("Connecting to a selected database...");
      conn = DriverManager.getConnection(DB_URL, USER, PASS);
      System.out.println("Connected database successfully.");

      stmt = conn.createStatement();
      String sql = "SELECT Password FROM users WHERE LogName = " + name;
      ResultSet resultSet = stmt.executeQuery(sql);
      while (resultSet.next()) {
        player.Password = resultSet.getString("Password");
      }
      stmt = conn.createStatement();
      sql = "SELECT AccType FROM users WHERE LogName = " + name;
      resultSet = stmt.executeQuery(sql);
      while (resultSet.next()) {
        player.AccType = resultSet.getString("Password");
      }
      player.LogName = name;

    } catch (SQLException e) {
      e.printStackTrace();
    }
    finally {
      try {
        if (conn != null) {
          conn.close();
        }
      } catch (SQLException e) {
        e.printStackTrace();
      }
    }
    System.out.println("--END--");
    return player;
  }
}