/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package i.shatalov.teamproject.database;

import java.sql.*;

public class updateDB {
    // JDBC driver name and database URL
    static final String JDBC_DRIVER = "com.mysql.jdbc.Driver";
    static final String DB_URL = "jdbc:mysql://localhost:3306/users";

    //  Database credentials
    static final String USER = "root";
    static final String PASS = "Pai4Piqwerty";

    public void insertNewRecords(int id, String logname, String pass, String acctype) {
        Connection conn = null;
        Statement stmt = null;
        try {
            //STEP 2: Register JDBC driver
            Class.forName(JDBC_DRIVER);

            //STEP 3: Open a connection
            System.out.println("Connecting to a selected database...");
            conn = DriverManager.getConnection(DB_URL, USER, PASS);
            System.out.println("Connected database successfully.");
            stmt = conn.createStatement();
            String sql = "SELECT id FROM login";
            ResultSet resultSet = stmt.executeQuery(sql);
            int ifCheck = 0;
            while (resultSet.next()){
                ifCheck = resultSet.getInt("id");
            }
            if (ifCheck != id) {
                System.out.println("Record with given id already exist");
                return;
            }
            System.out.println("Inserting given records in the table...");
            stmt = conn.createStatement();
            sql = "INSERT INTO login " +
                    "VALUES (" + id + ", \'" + logname +
                    "', \'" + pass + "', \'" + acctype + "' )";
            stmt.executeUpdate(sql);
            System.out.println("Records inserted.");
        } catch (SQLException se) {
            //Handle errors for JDBC
            se.printStackTrace();
        } catch (Exception e) {
            //Handle errors for Class.forName
            e.printStackTrace();
        } finally {
            //finally block used to close resources
            try {
                if (conn != null)
                    conn.close();
            } catch (SQLException se) {
                se.printStackTrace();
            }//end finally try
        }//end try
    }


    public String takeRecord(int id, String Record) {

        Connection conn = null;
        Statement stmt = null;
        String askedRecord = null;
        try {
            //STEP 2: Register JDBC driver
            Class.forName(JDBC_DRIVER);

            //STEP 3: Open a connection
            System.out.println("Connecting to a selected database...");
            conn = DriverManager.getConnection(DB_URL, USER, PASS);
            System.out.println("Connected database successfully.");

            System.out.println("Creating statement...");

            stmt = conn.createStatement();
            String sql = "SELECT " + Record +
                    " FROM login WHERE id = " + id;
            ResultSet resultSet = stmt.executeQuery(sql);
            while (resultSet.next()) {
                askedRecord = resultSet.getString(Record);
                System.out.println(Record + ": " + askedRecord);
            }

        } catch (SQLException se) {
            //Handle errors for JDBC
            se.printStackTrace();
        } catch (Exception e) {
            //Handle errors for Class.forName
            e.printStackTrace();
        } finally {
            //finally block used to close resources
            try {
                if (conn != null)
                    conn.close();
            } catch (SQLException se) {
                se.printStackTrace();
            }//end finally try
        }//end try
        return askedRecord;
    }

    public void updateRecord(int id, String Record, String newValue) {

        Connection conn = null;
        Statement stmt = null;

        try {
            //STEP 2: Register JDBC driver
            Class.forName(JDBC_DRIVER);

            //STEP 3: Open a connection
            System.out.println("Connecting to a selected database...");
            conn = DriverManager.getConnection(DB_URL, USER, PASS);
            System.out.println("Connected database successfully.");

            System.out.println("Creating statement...");

            stmt = conn.createStatement();
            String sql = "UPDATE login " + "SET " + Record + " = \'" + newValue +
                    "' WHERE id = " + id;
            stmt.executeUpdate(sql);

        } catch (SQLException se) {
            //Handle errors for JDBC
            se.printStackTrace();
        } catch (Exception e) {
            //Handle errors for Class.forName
            e.printStackTrace();
        } finally {
            //finally block used to close resources
            try {
                if (conn != null)
                    conn.close();
            } catch (SQLException se) {
                se.printStackTrace();
            }//end finally try
        }//end try
    }

}