/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package lobbymanager

class LobbyClass implements Lobby {
    private int minPlayersCount
    private int maxPlayersCount
    private int playersCount

    List<Player> players

    Level level

    LobbyClass(int minPlayersCount, int maxPlayersCount, Level level) {
        this.minPlayersCount = minPlayersCount
        this.maxPlayersCount = maxPlayersCount
        this.level = level

        playersCount = 0
        players = new ArrayList<>()
    }

    @Override
    void addPlayer(Player player) {
        if (playersCount >= maxPlayersCount) {
            throw new Exception("No more room for players")
        }
        if (!players.contains(player)) {
            playersCount++
            players.add(player)
        }
    }

    @Override
    void removePlayer(Player player) {
        if (players.contains(player)) {
            players.remove(player)
            playersCount--
        }
    }

    @Override
    SimulationResult simulate() {
        if (playersCount < minPlayersCount) {
            throw new IllegalStateException("Not enough players")
        }
        if (playersCount > maxPlayersCount) {
            throw new IllegalStateException("Too many players")
        }
        return null
    }

    @Override
    int getMinPlayersCount() {
        return minPlayersCount
    }

    @Override
    int getMaxPlayersCount() {
        return maxPlayersCount
    }

    @Override
    int getPlayersCount() {
        return 0
    }
}
