/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */

package simulator

import com.sun.net.httpserver.HttpServer
import groovy.json.JsonSlurper


class App {
    static int PORT = 1337


    static void main(String[] args) {
        HttpServer.create(new InetSocketAddress(PORT), /*max backlog*/ 0).with {
            println "Server is listening on ${PORT}, hit Ctrl+C to exit."
            createContext("/simulate") { http ->
                try {
                    http.responseHeaders.add("Content-type", "text/plain")
                    if (http.requestMethod != "POST") {
                        println "Wrong method"
                        http.sendResponseHeaders(404, 0)
                        http.close()
                        return
                    }
                    http.sendResponseHeaders(200, 0)

                    task = new Task("${http.requestBody}")
                    String result = task.run()
                    http.close()
                } catch (Exception e) {
                    println "Exception when processing solution"
                    println(e)
                    http.sendResponseHeaders(500, 0)
                    http.responseBody.withWriter { out ->
                        out << "error"
                    }
                    http.close

                }
            }
            start()
        }
    }
}
