/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package i.shatalov.teamproject.database;

import org.junit.Test;
import static org.junit.Assert.*;

/*public class readAndPutTest {
    @Test public void testAppHasAGreeting() {
        updateUser classUnderTest = new updateUser();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}*/
