/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package i.shatalov.teamproject.database;

import org.junit.Test;
import static org.junit.Assert.*;

public class test {
    @Test public void test() throws ClassNotFoundException {
        useDB db = new useDB();
        PlayerClass player = db.getPlayerByName("morozz");
        System.out.println(player.getName());
        System.out.println(player.getPass());
        System.out.println(player.getAcc());
    }
   /* @Test
    public void testLvl() {
        useDB db = new useDB();
        db.saveLevel(new LevelClass());
    }*/
}
