/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package i.shatalov.teamproject.database;

import org.junit.Test;
import static org.junit.Assert.*;

public class test {
    @Test public void test() throws ClassNotFoundException {
        useDB db = new useDB();
        db.savePlayer(new PlayerClass("morozz", "123coc321", "student"));
    }
    @Test
    public void testLvl() {
        useDB db = new useDB();
        db.saveLevel(new LevelClass());
    }
}
